development:
  email_user: 'hello@hobbyst.co'
  email_password: 'myhobby123'
  email_bcc: 'theone.kedia@gmail.com'
  redis_port: '6379'
  redis_host: 'localhost'

production:
  email_user: 'hello@hobbyst.co'
  email_password: 'myhobby123'
  email_bcc: 'theone.kedia@gmail.com'
  redis_port: '6379'
  redis_host: 'localhost'